Update hugo-build.yml

diff --git a/.github/workflows/hugo-build.yml b/.github/workflows/hugo-build.yml
--- a/.github/workflows/hugo-build.yml
+++ b/.github/workflows/hugo-build.yml
@@ -26,3 +26,27 @@ jobs:
 
     - name: Build website
       run: hugo
+
+    # Publish built docs to gh-pages branch.
+    # ===============================
+    - name: Commit website changes
+      run: |
+        rm -rf docs # not sure if this is needed...
+        mkdir docs
+        cp -rf public/* docs/
+        cd docs
+        echo "nathanpetersen.com" > CNAME
+        touch .nojekyll # need this due to "_*" dirs getting ignored by GitHub
+        git config --local user.email "action@github.com"
+        git config --local user.name "GitHub Action"
+        git add .
+        git commit -m "Update website" -a || true
+        # The above command will fail if no changes were present, so we ignore that.
+    - name: Push changes
+      uses: ad-m/github-push-action@master
+      with:
+        branch: gh-pages
+        force: true
+        directory: docs
+        github_token: ${{ secrets.GITHUB_TOKEN }}
+    # ===============================
